---
- name: "Capstone Configurations"
  hosts: all
  user: ubuntu
 
  vars:
    ansible_python_interpreter: /usr/bin/python3
    host_key_checking: False
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    # Get the environment variables from CircleCI and add to the instance
    CIRCLE_WORKFLOW_ID: "{{ lookup('env','CIRCLE_WORKFLOW_ID') }}"
    

  gather_facts: true

  roles:
    - configure-server
    - deploy